### ISSUE TITLE
Tr3.0 自动替换非法字符

### ISSUE THREAD

**Issue by X1A0CA1** [ChisBread/transmission_pt_edition#1]
Tr3.0 有一个特性是全平台统一字符，也就意味着一些在 Linux 下合法但在 Windows 不合法的字符会被强制替换为 " - "，如：" [ ", " ? "。

这导致了其他客户端下载好的种子自动加入Tr 保种以后，就无法在其他客户端继续做种。

翻了下源码，貌似是这块控制了这个功能，求大佬干掉这个功能。感谢！
https://github.com/transmission/transmission/blob/7f2578008d2fc723f1ea07d774a7c306b475b319/libtransmission/wildmat.c

**Comment by ChisBread** [comment]
你好，
简单看了一下，tr_wildmat实现的是类似通配符的功能。代码中仅在在判断AllowAddress/HostName时使用。
你说的'['会被替换为'-'，我也并没有复现。
