### ISSUE TITLE
如何改变配置文件的内容

### ISSUE THREAD

**Issue by jsdfhasuh** [ChisBread/transmission_pt_edition#11]
我尝试改了config文件夹下的settings.json里的参数，但是没办法生效，每一次重启容器都会恢复原样，请问如何改呢
{
    "alt-speed-down": 100,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 1,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": false,
    "download-dir": "/downloads/cosplay/raw",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "pidfile": "/var/transmission.pid",
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{f274b1bad048e11c7f57bde154e6593ff538aeb5HAfY3EwV",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "jsdfhasuh",
    "rpc-whitelist": "",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/config/transmission_ql.sh",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 1660,
    "speed-limit-up-enabled": true,
    "start-added-torrents": false,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": false,
    "watch-dir": "/watch",
    "watch-dir-enabled": true
}

**Comment by ChisBread** [comment]
这是因为退出transmission进程时，内存里的配置会回写到硬盘，覆盖硬盘上的settings
有两个简单的办法，一是容器暂停时修改，二是在WebUI中修改

**Comment by jsdfhasuh** [comment]
> 这是因为退出transmission进程时，内存里的配置会回写到硬盘，覆盖硬盘上的settings
> 有两个简单的办法，一是容器暂停时修改，二是在WebUI中修改

容器暂停后，我改了本地的文件，但重启后，仍然会回写，webui没有这个选项

**Comment by ChisBread** [comment]
> > 这是因为退出transmission进程时，内存里的配置会回写到硬盘，覆盖硬盘上的settings
> > 有两个简单的办法，一是容器暂停时修改，二是在WebUI中修改
> 
> 容器暂停后，我改了本地的文件，但重启后，仍然会回写，webui没有这个选项

部分环境变量中的设置，会被环境变量覆盖

**Comment by jsdfhasuh** [comment]
> > > 这是因为退出transmission进程时，内存里的配置会回写到硬盘，覆盖硬盘上的settings
> > > 有两个简单的办法，一是容器暂停时修改，二是在WebUI中修改
> > 
> > 容器暂停后，我改了本地的文件，但重启后，仍然会回写，webui没有这个选项
> 
> 部分环境变量中的设置，会被环境变量覆盖

我在官方的文档里，也没找到有关于内容rpc-authentication-required。我想更改这个选项，让其不需要密码验证
