### ISSUE TITLE
TransmissionPT3_3.0_arm_64.qpkg 威联通532x安装问题

### ISSUE THREAD

**Issue by cooltnt** [ChisBread/transmission_pt_edition#3]
之前用的3.0.2版本， 用qnapclub安装。
1、能安装，但是无数字签名，所以不确定是不是这个造成最后为正常启动的原因；
2、安装后在 appcenter中显示是启动的，看图片，图标颜色正常，下面也是显示【打开】
![image](https://user-images.githubusercontent.com/41370387/154798632-b63b96e7-99c5-4173-af50-9b2735483809.png)
3、ssh连接后，ps 无法找到transmission进程。（setting.json无论是按安装默认，还是替换成原来能正常使用的，改过端口，改过密码配置都不行）。
不知道有没有用威联通的朋友，有没有成功安装的经验可以分享下

**Comment by ChisBread** [comment]
无数字签名是正常的，arm64版本经过实测可以使用。建议提供启动日志方便进一步排查问题。
官方QQ群里有在使用这个版本的群友，群号是546612781。

**Comment by jifengguo** [comment]
威联通我的X86_64安装后正常使用。就是Win版本，Win11安装不上，运行star脚本一闪而过，没安装成功。

**Comment by cooltnt** [comment]
![image](https://user-images.githubusercontent.com/41370387/157665932-360d3020-8692-445d-b068-5be1b8b55a15.png)
发现执行文件的大小和正在用的差别很大，怎么会只有几百k，我之前在其他地方编译完的也是m级

**Comment by ChisBread** [comment]
动态链接和静态链接的区别
