### ISSUE TITLE
freebsd编译安装后速度没有提升

### ISSUE THREAD

**Issue by fierceX** [ChisBread/transmission_pt_edition#4]
你好，我编译后的版本，校验的时候还是很慢，切换按钮好像速度没有变化，是我编译的不对吗。我在编译的过程中cmake出现了一个错误：
提示在`ibtransmission/CMakeLists.txt`中 找不到`subprocess-test.cmd`，我把该文件中的这行`set(subprocess-test_ADD_SOURCES subprocess-test.cmd)`注释掉后，能够成功编译
系统是freebsd 13，应该和linux没有太多差异

**Comment by ChisBread** [comment]
Hi, 找到日志文件

**Comment by fierceX** [comment]
@ChisBread 我检查了，日志中有出现“Verify with fast hash check”，种子内容是多个MKV文件，大小都在10G以上，也有50G以上的单个MKV文件。第三个带校验的种子是否和原种子一致是什么意思，我是从普通的tr的种子文件夹里复制过来的，校验文件也是一样的

**Comment by ChisBread** [comment]
有“Verify with fast hash check”意味着快速校验正常工作

**Comment by ChisBread** [comment]
可以考虑试试docker版，做一下对比

**Comment by fierceX** [comment]
@ChisBread 就是因为用的是freebsd系统，没办法用docker所以才手动编译的。我刚刚重新编译安装，发现慢的有点厉害，比直接安装的tr3.0还要慢，校验结束后会出现`Verify with fast hash check`，大概57G的mkv文件，校验了40分钟。
<img width="1435" alt="截屏2022-03-25 14 38 46" src="https://user-images.githubusercontent.com/13912058/160067894-2bd33959-f98e-4985-9526-dad847bad0d0.png">

**Comment by ChisBread** [comment]
看起来你是使用debug模式编译的。
参考这个patch修改一下代码吧
https://github.com/ChisBread/transmission_skip_patch/blob/master/howtobuild/dsm/cross/transmission/patches/001-no-debug.patch

**Comment by fierceX** [comment]
我是用cmake构建的：
```bash
cmake ..
make
make insatll
```
我看你发的这个patch是修改的`configure`里的内容
不过我查了查资料，在`CMakeLists.txt`文件里，增加了`O3`选项。编译后的二进制文件确实小了不少，从原来的1.1M减少到了800+K，然后试了下同样的文件，速度快了不少。但是感觉还是不够快。
下图是新的校验速度，大佬看下正不正常
<img width="1436" alt="截屏2022-03-25 21 12 46" src="https://user-images.githubusercontent.com/13912058/160127733-22cc63be-e643-4b56-9cac-e303caaaa0ea.png">

**Comment by fierceX** [comment]
直接安装的tr3.0，同样地文件校验，只花了5分钟，看起来好像哪里还是有问题

**Comment by ChisBread** [comment]
我试试在FreeBSD上release

**Comment by fierceX** [comment]
谢谢大佬

**Comment by ChisBread** [comment]
1. 安装构建依赖
`pkg install libcurl  pkgconf devel/libevent libevent openssl intltool gettext lang/gcc gmake automake`
2. 参考[https://github.com/ChisBread/transmission_skip_patch/blob/master/howtobuild/dsm/cross/transmission/patches/001-no-debug.patch](patch)修改configure 
3. configure
`HAVE_CXX=yes ./configure --disable-nls --enable-daemon --enable-utp --prefix=$PWD/release`
4. 构建
`gmake` or `gmake install`


尝试以上步骤，可以得到和我一样的构建结果

**Comment by ChisBread** [comment]
或者试试我构建的[transmission_x64-freebsd-13.zip](https://github.com/ChisBread/transmission_pt_edition/releases/download/3.0-r7/transmission_x64-freebsd-13.zip)

脚本install_deps.sh 描述了基本的依赖

**Comment by fierceX** [comment]
@ChisBread 谢谢大佬，直接用configure构建报pkg_config包太老的错误，但是直接用你构建的包是可以用的，谢谢大佬，构建我再研究下

**Comment by ChisBread** [comment]
功能正常的话给个反馈，这个issue要close了

**Comment by fierceX** [comment]
freebsd 13上功能正常，后面更新可以考虑带着freebsd 13的包。用freenas和truenas的用户还是有一些的
