### ISSUE TITLE
docker for mac 环境下使用, 有下载和上传的情况下, cpu 占用持续超高. 没有下载和上传基本无占用

### ISSUE THREAD

**Issue by NansenLH** [ChisBread/transmission_pt_edition#6]
docker desktop 版本: 4.5.0
Mac os: 10.15.7;  intel i5 双核, 16G

**Comment by ChisBread** [comment]
macOS下的docker基于qemu, 相当于虚拟机
在不支持硬件虚拟化时，性能降低是合理的

暂无计划对非Linux平台提供支持。有需求可以自行编译macOS版本，应该不会有太多困难。
