### ISSUE TITLE
大佬，可以帮忙测试一下吗

### ISSUE THREAD

**Issue by jsdfhasuh** [ChisBread/transmission_pt_edition#8]
transmission-remote的命令都无法运行
都反馈这样的结果
nexpected response: <h1>401: Unauthorized</h1><p>Unauthorized User. 13 unsuccessful login attempts.</p>
我尝试通过注册 传入auth的参数，虽然没有反馈
transmission-remote --auth  transmission:transmission
但仍然不可运行transmission-remote

**Comment by ChisBread** [comment]
事实上transmission-remote不在本项目的修改范围内
况且你提供的信息不够
WebUI能否正常登陆？如果正常，建议看一下transmission官方文档
